[project]
name = "ai_beta_project"
version = "0.1.0"
description = "Does LLMs Speak the language of computers?"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pydantic>=2.11.7",
    "torch>=2.8.0",
    "transformers>=4.56.1",
]
